// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrnpH94foRxR5lU0ERRKGIHqK30EevEA',
    appId: '1:537346013974:android:a20769e5d26112de6eae37',
    messagingSenderId: '537346013974',
    projectId: 'antrean-dokter',
    databaseURL: 'https://antrean-dokter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'antrean-dokter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSkR7MsfxXq-4-DAXqL9tSkRaDvhH0YU',
    appId: '1:537346013974:ios:ceb0c16b36f0cd536eae37',
    messagingSenderId: '537346013974',
    projectId: 'antrean-dokter',
    databaseURL: 'https://antrean-dokter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'antrean-dokter.appspot.com',
    iosBundleId: 'com.noki.noGarco',
  );

}